import { MatchData } from "./types";

const testMatchData: MatchData = {
  meta: {
    data_version: "1.0.0",
    created: "2014-03-17",
    revision: 1,
  },
  info: {
    balls_per_over: 6,
    city: "Chittagong",
    dates: ["2014-03-16"],
    event: {
      group: "A",
      match_number: 2,
      name: "World T20",
      stage: "First Round",
    },
    gender: "male",
    match_type: "T20",
    match_type_number: 367,
    officials: {
      match_referees: ["J Srinath"],
      reserve_umpires: ["S Ravi"],
      tv_umpires: ["PR Reiffel"],
      umpires: ["Aleem Dar", "RJ Tucker"],
    },
    outcome: {
      by: {
        runs: 80,
      },
      winner: "Nepal",
    },
    overs: 20,
    player_of_match: ["SP Gauchan"],
    players: {
      "Hong Kong": [
        "Irfan Ahmed",
        "Waqas Barkat",
        "JJ Atkinson",
        "Babar Hayat",
        "MS Chapman",
        "Nizakat Khan",
        "Tanwir Afzal",
        "Aizaz Khan",
        "Najeeb Amar",
        "Haseeb Amjad",
        "Nadeem Ahmed",
      ],
      Nepal: [
        "SP Khakurel",
        "Sagar Pun",
        "G Malla",
        "P Khadka",
        "B Bhandari",
        "S Vesawkar",
        "B Regmi",
        "NB Budayair",
        "SP Gauchan",
        "Sompal Kami",
        "JK Mukhiya",
      ],
    },
    registry: {
      people: {
        "Aizaz Khan": "f6c2659d",
        "Aleem Dar": "f02778d1",
        "B Bhandari": "82342b13",
        "B Regmi": "98d05440",
        "Babar Hayat": "fbb657bb",
        "G Malla": "b2e1d224",
        "Haseeb Amjad": "fb0abc20",
        "Irfan Ahmed": "5c124657",
        "J Srinath": "bad31fac",
        "JJ Atkinson": "bf2d865c",
        "JK Mukhiya": "f8dcfe4e",
        "MS Chapman": "7fa12533",
        "NB Budayair": "9d280648",
        "Nadeem Ahmed": "023f6b02",
        "Najeeb Amar": "25e26a23",
        "Nizakat Khan": "e3eb9e46",
        "P Khadka": "12c3ba4d",
        "PR Reiffel": "c9354f29",
        "RJ Tucker": "38810cfc",
        "S Ravi": "9b9ee0df",
        "S Vesawkar": "3de06845",
        "SP Gauchan": "2d8aae2f",
        "SP Khakurel": "9a6b71d1",
        "Sagar Pun": "3c4007d3",
        "Sompal Kami": "1adb8ee8",
        "Tanwir Afzal": "5f5ca1a7",
        "Waqas Barkat": "a2eac9df",
      },
    },
    season: "2013/14",
    team_type: "international",
    teams: ["Hong Kong", "Nepal"],
    toss: {
      decision: "field",
      winner: "Hong Kong",
    },
    venue: "Zahur Ahmed Chowdhury Stadium",
  },
  innings: [
    {
      team: "Nepal",
      overs: [
        {
          over: 0,
          deliveries: [
            {
              batter: "SP Khakurel",
              bowler: "Tanwir Afzal",
              non_striker: "Sagar Pun",
              runs: {
                batter: 3,
                extras: 0,
                total: 3,
              },
            },
            {
              batter: "Sagar Pun",
              bowler: "Tanwir Afzal",
              non_striker: "SP Khakurel",
              runs: {
                batter: 0,
                extras: 0,
                total: 0,
              },
            },
            {
              batter: "Sagar Pun",
              bowler: "Tanwir Afzal",
              non_striker: "SP Khakurel",
              runs: {
                batter: 1,
                extras: 0,
                total: 1,
              },
            },
            {
              batter: "SP Khakurel",
              bowler: "Tanwir Afzal",
              non_striker: "Sagar Pun",
              runs: {
                batter: 0,
                extras: 0,
                total: 0,
              },
            },
            {
              batter: "SP Khakurel",
              bowler: "Tanwir Afzal",
              non_striker: "Sagar Pun",
              runs: {
                batter: 4,
                extras: 0,
                total: 4,
              },
            },
            {
              batter: "SP Khakurel",
              bowler: "Tanwir Afzal",
              non_striker: "Sagar Pun",
              runs: {
                batter: 0,
                extras: 0,
                total: 0,
              },
            },
          ],
        },
      ],
    },
  ],
};
